/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarruselPrincipal: typeof import('./src/components/CarruselPrincipal.vue')['default']
    DescriptionProduct: typeof import('./src/components/DescriptionProduct.vue')['default']
    HeroProduct: typeof import('./src/components/HeroProduct.vue')['default']
    Layout: typeof import('./src/components/layout.vue')['default']
    MainFooter: typeof import('./src/components/MainFooter.vue')['default']
    MenuSecundario: typeof import('./src/components/MenuSecundario.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TarjetasProductos: typeof import('./src/components/TarjetasProductos.vue')['default']
  }
}
